### ISSUE TITLE
Editor is always in dark mode

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditor#693]
### Description

<img width="1110" alt="image" src="https://github.com/AuroraEditor/AuroraEditor/assets/1290461/6f05e481-96f6-45a6-b7cd-0c98205d156e">

### To Reproduce

See 1

### Expected behavior

Light mode

### Version information

.

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by boscojwho** [comment]
Issue is caused by hard-coded colour hex values in `CodeEditorWrapperView` (see `.defaultTheme`), pretty easy fix:
1. Need someone to pick a default light theme for `EditorTheme`.
2. Change `CodeEditorWrapperView` so it responds to theme changes.

My understanding is that the ideal way to do this would be to define a light theme for the editor in `AuroraTheme.EditorColors`, then map that value to an `EditorTheme` value.

**Comment by boscojwho** [comment]
@aurora-care-bear please assign me

**Comment by aurora-care-bear** [comment]
@boscojwho You are assigned now, to unassign comment `@aurora-care-bear please unassign me`.

**Comment by 0xWDG** [comment]
Fixed in https://github.com/AuroraEditor/AuroraEditor/pull/745
